# kubectl create ns sentry
# kubens sentry
# helm install --wait -f values.yaml sentry --namespace sentry stable/sentry

####cat values.yaml


#####################SENTRY HELM#################################
user:
  create: true
  email: nicolas@r.com
  password: sentrytest
image:
  tag: 9.1.2
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  repository: sentry
web:
  replicacount: 1
cron:
  replicacount: 1
worker:
  replicacount: 2
email:
  backend: 
  host: 
  port: 
  user: 
  password: 
  use_tls: true
  from_address: 
service:
  annotations: {}
  externalPort: 9000
  internalPort: 9000
  name: sentry
  type: LoadBalancer
filestore:
  backend: filesystem
  filesystem:
    path: /var/lib/sentry/files
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      persistentWorkers: false
      size: 16Gi
############Conexiones externas: RDS y ElasticCache###############
#
postgresql:
  enabled: false
  postgresqlUsername: sentry
  postgresqlDatabase: sentry
  postgresqlHost: sentry-naws.com  #host rds de aws
  postgresqlPassword: sentrysentry
externalPostgresql:
  host: sentry-test-k8naws.com  #host rds de aws
  port: 5432
  username: sentry
  password: sentrysentry
  database: sentry
#
redis:
  enabled: false
  host: stg-sentraws.com   #host elasticcache de aws
  port: 6379
  #  nameOverride: stg-sentry-k8s  #host elasticcache de aws
  master:
    persistence:
      enabled: true
externalRedis:
  host: stg-sentry-kazonaws.com  #host elasticcache de aws
  port: 6379


